name: parabeac_test
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.19.4 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/parabeac_test/assets/images/ellipse.png
    - packages/parabeac_test/assets/images/backarrowcustom.svg
    - packages/parabeac_test/assets/images/backarrow.svg
